### ISSUE TITLE
 PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000] [2002] No such file or directory in /opt/lampp/htdocs/product_crud/03_good/Database.php:12

### ISSUE THREAD

**Issue by frankndungu** [dosha10/products_crud#2]
Stack trace:
#0 /opt/lampp/htdocs/product_crud/03_good/Database.php(12): PDO->__construct()
#1 /opt/lampp/htdocs/product_crud/03_good/Router.php(12): app\Database->__construct()
#2 /opt/lampp/htdocs/product_crud/03_good/public/index.php(8): app\Router->__construct()
#3 {main}

**Comment by frankndungu** [comment]
```
$this->pdo = new \PDO('mysql:host=127.0.0.1;port=3306;dbname=products_crud', 'root', '');
````
